name: cabinet
description: "web archiver for android devices"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  http: ^1.1.2
  json_annotation: ^4.8.1
  form_builder_validators: ^9.1.0
  flutter_form_builder: ^9.1.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true
