name: cabinet
description: "web archiver for android devices"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  http: ^1.1.2
  json_annotation: ^4.8.1
  form_builder_validators: ^9.1.0
  flutter_form_builder: ^9.1.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  objectbox: ^2.4.0
  objectbox_flutter_libs: any
  provider: ^6.1.1
  path: ^1.8.3
  path_provider: ^2.1.1
  html_unescape: ^2.0.0
  responsive_grid: ^2.4.4
  darq: ^2.0.0
  intl: ^0.18.1
  filesize: ^2.0.1
  flutter_html: ^3.0.0-beta.2
  video_player: ^2.8.1
  chewie: ^1.7.4
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.6.0
  objectbox_generator: any

flutter:
  uses-material-design: true
